export const options = [
    {value: "HTML5", label: "html"},
    {value: "CSS3", label: "css"},
    { value: "JavaScript", label: "javascript" },
    {value: "React", label: "react"},
    {value: "Redux", label: "redux"},
    {value: "TypeScript", label: "typescript"},
    { value: "Responsive Design", label: "responsive_design" },
    { value: "UI/UX", label: "ui_ux" },
    { value: "Frontend Frameworks", label: "frontend_frameworks" },
    { value: "Web Animation", label: "web_animation" },
    { value: "Webpack", label: "webpack" },
    { value: "Babel", label: "babel" },
    { value: "Sass", label: "sass" },
    { value: "LESS", label: "less" },
    { value: "Vue.js", label: "vuejs" },
    { value: "Angular", label: "angular" },
    { value: "jQuery", label: "jquery" },
    { value: "Web Components", label: "web_components" },
    { value: "Progressive Web Apps", label: "pwa" },
    { value: "Cross-Browser Compatibility", label: "cross_browser_compat" },
    { value: "Node.js", label: "nodejs" },
    { value: "Express.js", label: "expressjs" },
    { value: "Django", label: "django" },
    { value: "Flask", label: "flask" },
    { value: "Ruby on Rails", label: "ruby_on_rails" },
    { value: "PHP", label: "php" },
    { value: "RESTful API", label: "restful_api" },
    { value: "GraphQL", label: "graphql" },
    { value: "Database Design", label: "db_design" },
    { value: "MySQL", label: "mysql" },
    { value: "PostgreSQL", label: "postgresql" },
    { value: "MongoDB", label: "mongodb" },
    { value: "Authentication & Authorization", label: "auth_authz" },
    { value: "Server Deployment", label: "server_deployment" },
    { value: "Serverless", label: "serverless" },
    { value: "Microservices", label: "microservices" },
    { value: "Load Balancing", label: "load_balancing" },
    { value: "iOS Development", label: "ios_development" },
    { value: "Android Development", label: "android_development" },
    { value: "React Native", label: "react_native" },
    { value: "Flutter", label: "flutter" },
    { value: "Mobile UI Design", label: "mobile_ui_design" },
    { value: "App Architecture", label: "app_architecture" },
    { value: "Push Notifications", label: "push_notifications" },
    { value: "Offline Storage", label: "offline_storage" },
    { value: "Mobile Security", label: "mobile_security" },
    { value: "Performance Optimization", label: "performance_optimization" },
    { value: "Cross-Platform Development", label: "cross_platform_dev" },
    { value: "App Store Submission", label: "app_store_submission" },
    { value: "Mobile Testing", label: "mobile_testing" },
    { value: "AR/VR Integration", label: "ar_vr_integration" },
    { value: "DevOps", label: "devops" },
    { value: "Cloud Computing", label: "cloud_computing" },
    { value: "Containerization", label: "containerization" },
    { value: "Microservices Architecture", label: "microservices_arch" },
    { value: "Cybersecurity", label: "cybersecurity" },
    { value: "Data Science", label: "data_science" },
    { value: "Machine Learning", label: "machine_learning" },
    { value: "Artificial Intelligence", label: "artificial_intelligence" },
    { value: "Blockchain", label: "blockchain" },
    { value: "IoT (Internet of Things)", label: "iot" },
    { value: "Big Data", label: "big_data" },
    { value: "Natural Language Processing", label: "nlp" },
    { value: "Quantum Computing", label: "quantum_computing" },
    { value: "Ethical Hacking", label: "ethical_hacking" },
    { value: "Augmented Reality", label: "augmented_reality" },
    { value: "Virtual Reality", label: "virtual_reality" },
    { value: "Robotics", label: "robotics" },
    { value: "Code Version Control", label: "code_version_control" },
    { value: "Continuous Integration", label: "continuous_integration" },
    { value: "API Design", label: "api_design" },
    { value: "Server Administration", label: "server_administration" },
    { value: "Network Security", label: "network_security" },
    { value: "UI/UX Design", label: "ui_ux_design" },
    { value: "Responsive Web Design", label: "responsive_web_design" },
    { value: "User-Centered Design", label: "user_centered_design" },
    { value: "Game Development", label: "game_development" },
    { value: "Digital Marketing", label: "digital_marketing" },
    { value: "E-Commerce", label: "e_commerce" },
    { value: "Project Management", label: "project_management" },
    { value: "Agile Methodology", label: "agile_methodology" },
    { value: "Scrum", label: "scrum" },
    { value: "Kanban", label: "kanban" },
    { value: "IT Ethics", label: "it_ethics" },
    { value: "Green IT", label: "green_it" },
]